### ISSUE TITLE
troubles running Serial workflows with HTCondor, Singularity, and CVMFS unpacked images

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-workflow-engine-serial#222]
### Example 1: Snakemake workflow works well

When a researcher uses HTCondor and Singularity unpacked images, the Snakemake workflow works well.

Example of `reana.yaml`:

```yaml
inputs:
  files:
    - Snakefile
    - reana.yaml
workflow:
  type: snakemake
  file: Snakefile
outputs:
  files:
    - info.txt
```

Example of `Snakefile`:

```python
rule all:
  output:
    "info.txt"
  resources:
    kerberos=True,
    compute_backend="htcondorcern",
    unpacked_img=True
  container:
    "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/library/python:3.10"
  shell:
    """
    echo $SINGULARITY_NAME >> info.txt
    python --version >> info.txt
    """
```

### Example 2: Serial workflow does not work

However, a similar workflow using Serial workflow engine does not work well.

Example of `reana.yaml`:

```yaml
version: 0.6.0
workflow:
  type: serial
  specification:
    steps:
      - name: plotdata-htcondor
        environment: "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/library/python:3.11"
        compute_backend: htcondorcern
        htcondor_max_runtime: espresso
        kerberos: true
        unpacked_img: true
        commands:
          - python --version
```

The observed error is:

![Image](https://github.com/user-attachments/assets/4582c156-8a09-4923-8d24-52db7d45d4d5)

## Expected behaviour

All the supported workflow engines should support HTCondor with CVMFS unpacked images similarly well, just as Snakemake does.

Let's test Serial, but also CWL and Yadage in this respect.
